<a href="https://colab.research.google.com/github/varuncode01/P_Sentiment_Analysis/blob/main/P_Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Author  
**Varun Pal**

* LinkedIn - www.linkedin.com/in/varun-pal-955ba0357

* Github - https://github.com/varuncode01

# **Project Name** - **Sentiment Analysis**

#### 1. Loading Dataset

In [138]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [139]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/P_Sentiment_Analysis/train.csv', encoding = 'latin-1')

In [140]:
df

textID                                               text  \
0      cb774db0d1                I`d have responded, if I were going   
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
...           ...                                                ...   
27476  4eac33d1c0   wish we could come see u on Denver  husband l...   
27477  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27478  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27479  ed167662a5                         But it was worth it  ****.   
27480  6f7127d9d7     All this flirting going on - The ATG smiles...   

                                           selected_text sentiment  \
0                    I`d have responded, if I were going   neutral   
1                                               Sooo SAD  negative   
2                                            bullying me  negative   
3                                         leave me alone  negative   
4                                          Sons of ****,  negative   
...                                                  ...       ...   
27476                                             d lost  negative   
27477                                      , don`t force  negative   
27478                          Yay good for both of you.  positive   
27479                         But it was worth it  ****.  positive   
27480  All this flirting going on - The ATG smiles. Y...   neutral   

      Time of Tweet Age of User      Country  Population -2020  \
0           morning        0-20  Afghanistan          38928346   
1              noon       21-30      Albania           2877797   
2             night       31-45      Algeria          43851044   
3           morning       46-60      Andorra             77265   
4              noon       60-70       Angola          32866272   
...             ...         ...          ...               ...   
27476         night       31-45        Ghana          31072940   
27477       morning       46-60       Greece          10423054   
27478          noon       60-70      Grenada            112523   
27479         night      70-100    Guatemala          17915568   
27480       morning        0-20       Guinea          13132795   

       Land Area (Km²)  Density (P/Km²)  
0             652860.0               60  
1              27400.0              105  
2            2381740.0               18  
3                470.0              164  
4            1246700.0               26  
...                ...              ...  
27476         227540.0              137  
27477         128900.0               81  
27478            340.0              331  
27479         107160.0              167  
27480         246000.0               53  

[27481 rows x 10 columns]

#### 2. Handling null values and cleaning dataset

In [141]:
df.isnull().sum()

textID              0
text                1
selected_text       1
sentiment           0
Time of Tweet       0
Age of User         0
Country             0
Population -2020    0
Land Area (Km²)     0
Density (P/Km²)     0
dtype: int64

In [142]:
df.nunique()

textID              27481
text                27480
selected_text       22430
sentiment               3
Time of Tweet           3
Age of User             6
Country               195
Population -2020      195
Land Area (Km²)       193
Density (P/Km²)       136
dtype: int64

In [143]:
selected_columns = ['text', 'sentiment']
df2 = df[selected_columns]

In [144]:
df2

text sentiment
0                    I`d have responded, if I were going   neutral
1          Sooo SAD I will miss you here in San Diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       Sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see u on Denver  husband l...  negative
27477   I`ve wondered about rake to.  The client has ...  negative
27478   Yay good for both of you. Enjoy the break - y...  positive
27479                         But it was worth it  ****.  positive
27480     All this flirting going on - The ATG smiles...   neutral

[27481 rows x 2 columns]

In [145]:
df2.drop_duplicates(['text'], inplace = True)

In [146]:
df2

text sentiment
0                    I`d have responded, if I were going   neutral
1          Sooo SAD I will miss you here in San Diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       Sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see u on Denver  husband l...  negative
27477   I`ve wondered about rake to.  The client has ...  negative
27478   Yay good for both of you. Enjoy the break - y...  positive
27479                         But it was worth it  ****.  positive
27480     All this flirting going on - The ATG smiles...   neutral

[27481 rows x 2 columns]

### 3. Feature Engineering

#### Text Data Preprocessing

In [147]:
df2['text'] = df2['text'].astype(str)

In [148]:
df2

text sentiment
0                    I`d have responded, if I were going   neutral
1          Sooo SAD I will miss you here in San Diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       Sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see u on Denver  husband l...  negative
27477   I`ve wondered about rake to.  The client has ...  negative
27478   Yay good for both of you. Enjoy the break - y...  positive
27479                         But it was worth it  ****.  positive
27480     All this flirting going on - The ATG smiles...   neutral

[27481 rows x 2 columns]

In [149]:
df2['text'] = df2['text'].str.lower()

In [150]:
df2

text sentiment
0                    i`d have responded, if i were going   neutral
1          sooo sad i will miss you here in san diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see u on denver  husband l...  negative
27477   i`ve wondered about rake to.  the client has ...  negative
27478   yay good for both of you. enjoy the break - y...  positive
27479                         but it was worth it  ****.  positive
27480     all this flirting going on - the atg smiles...   neutral

[27481 rows x 2 columns]

In [151]:
df2.isnull().sum()

text         0
sentiment    0
dtype: int64

In [152]:
df2.dropna(inplace = True)

In [153]:
df2.isnull().sum()

text         0
sentiment    0
dtype: int64

In [154]:
#Expand and Contraction

In [155]:
!pip install contractions

In [156]:
import contractions

In [157]:
df2['text'] = df2['text'].apply(lambda x: contractions.fix(x))

In [158]:
df2

text sentiment
0                    i`d have responded, if i were going   neutral
1          sooo sad i will miss you here in san diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see you on denver  husband...  negative
27477   i`ve wondered about rake to.  the client has ...  negative
27478   yay good for both of you. enjoy the break - y...  positive
27479                         but it was worth it  ****.  positive
27480     all this flirting going on - the atg smiles...   neutral

[27481 rows x 2 columns]

In [159]:
#Removing stop words

In [160]:
import nltk

In [161]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [162]:
import nltk

In [163]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [164]:
# df2['text'] = df2['text'].apply(lambda x: x.split())

In [165]:
df2

text sentiment
0                    i`d have responded, if i were going   neutral
1          sooo sad i will miss you here in san diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see you on denver  husband...  negative
27477   i`ve wondered about rake to.  the client has ...  negative
27478   yay good for both of you. enjoy the break - y...  positive
27479                         but it was worth it  ****.  positive
27480     all this flirting going on - the atg smiles...   neutral

[27481 rows x 2 columns]

In [166]:
stop_words = set(stopwords.words('english'))

In [167]:
df2['text'] = df2['text'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stop_words]))

In [168]:
df2

text sentiment
0                                   i`d responded, going   neutral
1                             sooo sad miss san diego!!!  negative
2                                    boss bullying me...  negative
3                                 interview! leave alone  negative
4        sons ****, couldn`t put releases already bought  negative
...                                                  ...       ...
27476  wish could come see denver husband lost job ca...  negative
27477  i`ve wondered rake to. client made clear .net ...  negative
27478  yay good you. enjoy break - probably need hect...  positive
27479                                        worth ****.  positive
27480         flirting going - atg smiles. yay. ((hugs))   neutral

[27481 rows x 2 columns]

In [169]:
import re
import string
from bs4 import BeautifulSoup

In [170]:
df2['text'] = df2['text'].replace(string.punctuation, '')  # Remove punctuation

In [171]:
df2['text']

0                                     i`d responded, going
1                               sooo sad miss san diego!!!
2                                      boss bullying me...
3                                   interview! leave alone
4          sons ****, couldn`t put releases already bought
                               ...                        
27476    wish could come see denver husband lost job ca...
27477    i`ve wondered rake to. client made clear .net ...
27478    yay good you. enjoy break - probably need hect...
27479                                          worth ****.
27480           flirting going - atg smiles. yay. ((hugs))
Name: text, Length: 27481, dtype: object

In [172]:
df2['text'] = df2['text'].apply(lambda x: re.sub( r'[^\w\s]', '', x))  # Remove special characters

In [173]:
df2

text sentiment
0                                     id responded going   neutral
1                                sooo sad miss san diego  negative
2                                       boss bullying me  negative
3                                  interview leave alone  negative
4              sons  couldnt put releases already bought  negative
...                                                  ...       ...
27476  wish could come see denver husband lost job ca...  negative
27477  ive wondered rake to client made clear net onl...  negative
27478  yay good you enjoy break  probably need hectic...  positive
27479                                             worth   positive
27480                flirting going  atg smiles yay hugs   neutral

[27481 rows x 2 columns]

In [174]:
df2['text'] = df2['text'].apply(lambda x: re.sub(r'http\S+', '', x))  # Remove URLs

In [175]:
df2

text sentiment
0                                     id responded going   neutral
1                                sooo sad miss san diego  negative
2                                       boss bullying me  negative
3                                  interview leave alone  negative
4              sons  couldnt put releases already bought  negative
...                                                  ...       ...
27476  wish could come see denver husband lost job ca...  negative
27477  ive wondered rake to client made clear net onl...  negative
27478  yay good you enjoy break  probably need hectic...  positive
27479                                             worth   positive
27480                flirting going  atg smiles yay hugs   neutral

[27481 rows x 2 columns]

In [176]:
df2['sentiment'] = df2['sentiment'].replace({'positive': 2, 'neutral': 1, 'negative': 0})

In [177]:
df2

text  sentiment
0                                     id responded going          1
1                                sooo sad miss san diego          0
2                                       boss bullying me          0
3                                  interview leave alone          0
4              sons  couldnt put releases already bought          0
...                                                  ...        ...
27476  wish could come see denver husband lost job ca...          0
27477  ive wondered rake to client made clear net onl...          0
27478  yay good you enjoy break  probably need hectic...          2
27479                                             worth           2
27480                flirting going  atg smiles yay hugs          1

[27481 rows x 2 columns]

In [178]:
df2['text'] = df2['text'].astype(str)

In [179]:
df2['combine'] = df2['text'] + ' ' + df2['sentiment'].astype(str)

In [180]:
df2

text  sentiment  \
0                                     id responded going          1   
1                                sooo sad miss san diego          0   
2                                       boss bullying me          0   
3                                  interview leave alone          0   
4              sons  couldnt put releases already bought          0   
...                                                  ...        ...   
27476  wish could come see denver husband lost job ca...          0   
27477  ive wondered rake to client made clear net onl...          0   
27478  yay good you enjoy break  probably need hectic...          2   
27479                                             worth           2   
27480                flirting going  atg smiles yay hugs          1   

                                                 combine  
0                                   id responded going 1  
1                              sooo sad miss san diego 0  
2                                     boss bullying me 0  
3                                interview leave alone 0  
4            sons  couldnt put releases already bought 0  
...                                                  ...  
27476  wish could come see denver husband lost job ca...  
27477  ive wondered rake to client made clear net onl...  
27478  yay good you enjoy break  probably need hectic...  
27479                                           worth  2  
27480              flirting going  atg smiles yay hugs 1  

[27481 rows x 3 columns]

#### 5. Textual data into numerical

In [181]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [182]:
vector = TfidfVectorizer()

In [183]:
f_vector = vector.fit_transform(df2['text']) #Feature vectors

In [184]:
print(f_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 198671 stored elements and shape (27481, 28299)>
  Coords	Values
  (0, 12872)	0.48041582042041353
  (0, 20768)	0.8221018193734481
  (0, 11138)	0.3055310754614783
  (1, 22884)	0.42452535167131367
  (1, 21301)	0.3303528681328239
  (1, 16404)	0.3138588824434252
  (1, 21395)	0.5380956556369301
  (1, 7943)	0.5679708404493942
  (2, 4631)	0.5735236017409996
  (2, 5060)	0.7426759078122749
  (2, 15947)	0.3456923114581009
  (3, 13301)	0.6501294554183952
  (3, 14722)	0.515711060240142
  (3, 2519)	0.5580087755074912
  (4, 22868)	0.4836974956571012
  (4, 6886)	0.3585193879611218
  (4, 19985)	0.3328962571448684
  (4, 20585)	0.5425840609171851
  (4, 2535)	0.30703779987684926
  (4, 4656)	0.3714983033815483
  (5, 21925)	0.4787763456393501
  (5, 19275)	0.44725487130505553
  (5, 4074)	0.25031098454751066
  (5, 20221)	0.44725487130505553
  (5, 10291)	0.415733396970761
  :	:
  (27477, 10232)	0.25448378040310937
  (27477, 7884)	0.2919576310128656

#### 6. Model Implementation

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
from sklearn.metrics import accuracy_score

In [187]:
from sklearn.metrics import classification_report

In [188]:
from sklearn.metrics import confusion_matrix

In [189]:
# SVM, RandomForest, Gradient Boosting

In [190]:
# SVM

In [191]:
train_x, test_x, train_y, test_y = train_test_split(f_vector, df2['sentiment'], test_size=0.2, random_state=42)

In [192]:
from sklearn.svm import SVC

In [193]:
SVC_model = SVC(kernel='linear')

In [194]:
SVC_model.fit(train_x, train_y)

SVC(kernel='linear')

In [195]:
pred_y = SVC_model.predict(test_x)

In [196]:
# Accuracy Score

In [197]:
print("Testing Accuracy: ", accuracy_score(test_y, pred_y))

Testing Accuracy:  0.7002001091504457


In [198]:
print(classification_report(test_y, pred_y))

              precision    recall  f1-score   support

           0       0.75      0.59      0.66      1562
           1       0.63      0.78      0.70      2230
           2       0.78      0.70      0.74      1705

    accuracy                           0.70      5497
   macro avg       0.72      0.69      0.70      5497
weighted avg       0.71      0.70      0.70      5497



In [199]:
print(confusion_matrix(test_y, pred_y))

[[ 917  558   87]
 [ 247 1744  239]
 [  55  462 1188]]


In [200]:
#Random Forest

In [201]:
train_x, test_x, train_y, test_y = train_test_split(f_vector, df2['sentiment'], test_size=0.2, random_state=42)

In [202]:
from sklearn.ensemble import RandomForestClassifier

In [203]:
random_forest = RandomForestClassifier()

In [204]:
random_forest.fit(train_x, train_y)

RandomForestClassifier()

In [205]:
y_pred2 = random_forest.predict(test_x)

In [206]:
accuracy_score(test_y, y_pred2)

0.6960160087320356

In [207]:
print(classification_report(test_y, y_pred2))

              precision    recall  f1-score   support

           0       0.75      0.57      0.65      1562
           1       0.64      0.75      0.69      2230
           2       0.74      0.74      0.74      1705

    accuracy                           0.70      5497
   macro avg       0.71      0.69      0.69      5497
weighted avg       0.70      0.70      0.69      5497



In [208]:
print(confusion_matrix(test_y, y_pred2))

[[ 895  556  111]
 [ 236 1665  329]
 [  55  384 1266]]


In [209]:
# Gradient Boositng

In [210]:
from sklearn.ensemble import GradientBoostingClassifier

In [211]:
gradientboost = GradientBoostingClassifier()

In [212]:
train_x, test_x, train_y, test_y = train_test_split(f_vector, df2['sentiment'], test_size=0.2, random_state=42)

In [213]:
gradientboost.fit(train_x, train_y)

GradientBoostingClassifier()

In [214]:
pred_y3 = gradientboost.predict(test_x)

In [215]:
accuracy_score(test_y, pred_y3)

0.6365290158268146

In [216]:
print(classification_report(test_y, pred_y3))

              precision    recall  f1-score   support

           0       0.78      0.38      0.51      1562
           1       0.55      0.85      0.67      2230
           2       0.78      0.60      0.68      1705

    accuracy                           0.64      5497
   macro avg       0.70      0.61      0.62      5497
weighted avg       0.69      0.64      0.63      5497



In [217]:
print(confusion_matrix(test_y, pred_y3))

[[ 590  887   85]
 [ 134 1894  202]
 [  28  662 1015]]


#### 1. Text Data Preprocessing

#### 1. Text Data Preprocessing